sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        fFt8Xdxdj/njypWOO16O2W9H8hN9712T3Jr6EF+etXhAMw0HIUqzsPnTISDQjDbGcxXRyOxkmiM6K3KhUqhEtb52gMTq79+4u0hDHD6KaqZGxtSBU4Z1+gU7lfUyg6XXYayYaTau9kDMuG+sr2Jxc9+/hEnqe0W1uorYfx0eGjXpZydci8Lih3azFE0dJUkLJTpPX0Zpv9pDCVIVomnSGEjZbDKf91hTML39uKohQN+uF/4jwc0Rtm+4knlhOncEJO4AgrzZJZpBpXbuBxcbK10q9piDOcK0q5C9wgScMYj6q42D2qjkURwh/qjqDUQVYjn69g/WfzZORat/gEJdwcnDptrrwB+/qqla/14aYPykOEIatmi2zs5w641fYwFZ4TgHrf364USIsximeLl2ulHWTTK4Uk9E5kbzeMo7OyrHyNqrmoNDQJXbAE2mSdpA8n600NGkHPvnLNUSz6QkewsT+wQy6YCGHMIfVtEJSH4t4xNCukDW/NFp4ETakBQ7m8MT8HTZJs2A/l5UIFCImdkymHcKpLivwkm5RfIbBRi4igBHjCAcUvL/eBT+C9kh4GnXO2ayW3TCXRKlxshukbd1qgkUYLTKA7yuFjXIbzw6/XxKg6SEZwF3F6NMcSAsa4kUcAZm7cvyebwfJe2TcLiuzrICsbBazNBsb5yOhsc=
    - secure: >-
        ROzOj6qQl6/hwqKb+man2MsXWzW6gnhJGgQER1LnfWIIM+9Z6bYujZRp8o4yQ3gzgDy6jhE7RjwlijK1wHJyZ+s5MfX86BkKmku2SDq50jMlvpzovFHpcqjpDeRJjNWcSx493S6DwU7ODdaODQNxKW2Zi2VJ1v9j8DV5g0aHyrvlaFGSYjDcahMRiNJ6ePT5NkLDB/YyyM/D5s8R+2vAkHbTvoKHQIX4o+YVaSxowP5vh06T3h+0lgp4BqW7eK1dCbT4ZkFPLoaKwk/hUh+jejDEQXHfRQjp58j/J0cqIwhPwIIvXUHeEp9WLymA6CFiD8qx3MAsOTpCEIFqLtH4v9o+W22NCLxReEDtt82YLh36J4QRF/QSouJAztItZp10zy8UsM1xT0fvg2jtCan9gNpDFFGYtUX7jrvg2ahWDghRpDcUnRAQJiY+wtwc+GkFvm/1KngBIeW+2+bI3QHXw4SgzwIl/RGTFJdxGcahcWV6NJ4L+b2n8WIEBa5zrb9mO1vZxyVBwfZb8X5DfFJxThNdTk9vr/2bgxZEy82EPqVBYIdkGO/fFpgl1vWDsg1h4SbdFrM8OfudzTIk/dVvhRkQbrQC55RABF250bIsFOFSIzEHvuH0293UbnCZUfgzSBlnUC3tEO1dVsfIGOvz/vcEBko81XoIzhMWXeOLCKs=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
